package Model;
// Generated Dec 11, 2020 10:38:08 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Employee generated by hbm2java
 */
@Entity
@Table(name="employee"
    ,catalog="dbthuongmaidientu"
)
public class Employee  implements java.io.Serializable {


     private Integer employeeId;
     private String email;
     private String phone;
     private String address;
     private String employeeName;
     private String sex;
     private Integer salary;
     private Date paycheck;
     private Integer workdate;
     private Date lastAtt;

    public Employee() {
    }

	
    public Employee(String employeeName) {
        this.employeeName = employeeName;
    }
    public Employee(String email, String phone, String address, String employeeName, String sex, Integer salary, Date paycheck, Integer workdate, Date lastAtt) {
       this.email = email;
       this.phone = phone;
       this.address = address;
       this.employeeName = employeeName;
       this.sex = sex;
       this.salary = salary;
       this.paycheck = paycheck;
       this.workdate = workdate;
       this.lastAtt = lastAtt;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="EmployeeID", unique=true, nullable=false)
    public Integer getEmployeeId() {
        return this.employeeId;
    }
    
    public void setEmployeeId(Integer employeeId) {
        this.employeeId = employeeId;
    }

    
    @Column(name="Email", length=45)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="Phone", length=15)
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }

    
    @Column(name="Address", length=45)
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }

    
    @Column(name="EmployeeName", nullable=false, length=45)
    public String getEmployeeName() {
        return this.employeeName;
    }
    
    public void setEmployeeName(String employeeName) {
        this.employeeName = employeeName;
    }

    
    @Column(name="Sex", length=45)
    public String getSex() {
        return this.sex;
    }
    
    public void setSex(String sex) {
        this.sex = sex;
    }

    
    @Column(name="Salary")
    public Integer getSalary() {
        return this.salary;
    }
    
    public void setSalary(Integer salary) {
        this.salary = salary;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="Paycheck", length=10)
    public Date getPaycheck() {
        return this.paycheck;
    }
    
    public void setPaycheck(Date paycheck) {
        this.paycheck = paycheck;
    }

    
    @Column(name="Workdate")
    public Integer getWorkdate() {
        return this.workdate;
    }
    
    public void setWorkdate(Integer workdate) {
        this.workdate = workdate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="LastAtt", length=10)
    public Date getLastAtt() {
        return this.lastAtt;
    }
    
    public void setLastAtt(Date lastAtt) {
        this.lastAtt = lastAtt;
    }




}


