package Model;
// Generated Dec 14, 2020 12:54:47 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Revenue generated by hbm2java
 */
@Entity
@Table(name="revenue"
    ,catalog="dbthuongmaidientu"
)
public class Revenue  implements java.io.Serializable {


     private Integer id;
     private int revenue;
     private Date date;

    public Revenue() {
    }

	
    public Revenue(int revenue) {
        this.revenue = revenue;
    }
    public Revenue(int revenue, Date date) {
       this.revenue = revenue;
       this.date = date;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="revenue", nullable=false)
    public int getRevenue() {
        return this.revenue;
    }
    
    public void setRevenue(int revenue) {
        this.revenue = revenue;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="date", length=10)
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }




}


